### PR TITLE
Test new features

### PR DESCRIPTION
**Pull request by ducanh-ho2296**
- add new page quickstart for using our API services
- create new features for overview page and introduction page

### CODE REVIEW

**Comment by ducanh-ho2296** [comment]
@andrej-schreiner @Leonardthiele could you have a look on new changes, feel free to give me any feedback!

---

image

**Comment by andrej-schreiner** [comment]
I like this designuch more

**Comment by Leonardthiele** [comment]
I like it too. Looks much better

**Comment by ducanh-ho2296** [comment]
very nice, I will merge the changes then!

**Pull request merged**
